/* 
 *
 *  Do NOT edit this file! 
 *
 *
 */

/* Print 1-255
print1To255()
Print all the integers from 1 to 255. */



/* Print Ints and Sum 0-255
printIntsAndSum0To255()
Print integers from 0 to 255, and with each
integer print the sum so far. */



/* Print Max of Array
printMaxOfArray(arr)
Given an array, find and print its largest element. */



/* Return Odds Array 1-255
returnOddsArray1To255()
Create an array with all the odd integers between
1 and 255 (inclusive). */



/* Return Array Count Greater than Y
returnArrayCountGreaterThanY(arr, y)
Given an array and a value Y, count and print the
number of array values greater than Y. */



/* Print Max, Min, Average Array Values
printMaxMinAverageArrayVals(arr)
Given an array, print the max, min and average
values for that array. */



/* Swap String for Array Negative Values
swapStringForArrayNegativeVals(arr)
Given an array of numbers, replace any negative
values with the string 'Dojo'. */



/* Print Odds 1-255
printOdds1To255()
Print all odd integers from 1 to 255. */



/* Print Array Values
printArrayVals(arr)
Iterate through a given array, printing each value. */



/* Print Average of Array
printAverageOfArray(arr)
Analyze an array’s values and print the average. */



/* Square Array Values
squareArrayVals(arr)
Square each value in a given array, returning that
same array with changed values. */



/* Zero Out Array Negative Numbers
zeroOutArrayNegativeVals(arr)
Return the given array, after setting any negative
values to zero. */



/* Shift Array Values Left
shiftArrayValsLeft(arr)
Given an array, move all values forward (to the
left) by one index, dropping the first value and
leaving a 0 (zero) value at the end of the array. */


